---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAMKWO1ia10O6TNktt0DJ+/SB1Cd0hGD8fcgiTwq0QCmQrHiYkpt6XQQgpYJEatiJEmsScpXS3YNJJh3nFX0AA4GWMpJxwHvAhvRBEhpbxgnWH9g4Cygr/QWhe6md2uCbTqKikIWqLWhn5IxiQQttlY/Ug26hikf488hCTWB6ISwuHuXS+x0wSuvZGTn+nFC83XjQsP/BAvNS2FTz6SKCLv7X2wLxJ7QmIQhE425nvEBSTQtggiEXPT4jaq79dXvZac6lvs/LUHUCQ+bJ3OJASV3h2cU8VvELKAqV97/evKT/CnZM29YKADSYWWZy5YoFpfzAEmJ5UdgsgqH34xOTHl+F5Um/bmAvXbzqzvPD79zmv1kYOl0ZycalJ3jDUO7XHc3t/02Rm/UsU4Efou/m+XgGnyB7ovRjLaRHOoLLi4PQXh7tmWUBSVTRstEGp+K7X9jzpt5LVIjhOfLi42UQp2ssIONiJ+X4Ya3hq8d6QvNmef++h8k2zZPXtwOLcc/13oSdASGFmvRb5TgB3Th1qQOKpg8WJCvNCytiS+3kLmwbK7U3kVCXMoM4PQN2SHikVZFJNVG+0V8ShFIXmoK+CBPy0CkopuhMjaz9h8r1ApUsrefu5vU+/CV4xjhv9GSK1c5J5VgxqnnEKOKztDinlPd2EtblB3nQ6bxFEvPmUY7TE1xOtaPE7FWYCqMBU3BfqUQ0+cJQr+lpnVsqQge5GCN4NUhfyhK0/FKFyqnE1Cf/wWDacccNCcVJNo7Cy5A98I3Lfg2O+iyy2tyKbKlm+b/HTJWFSp52rWFPJGwZruoEc=
  template:
    metadata:
      creationTimestamp: null
      name: velero-credentials
      namespace: velero
