{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "velero-credentials",
    "namespace": "velero",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "velero-credentials",
        "namespace": "velero",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "cloud": "AgCK4rYEfoo2/R/WyqdB0/VAkI+5hnvxhRGdt1uu+dILY3wfFwM8SuSYG4sz4EmVOdN/YQ69haqy/FgCBT1Ab98Ci9t+b8ySjIAc2EQEXATSWMDgIClZ1aoNyy/yMA7bBIxKnw/rk8iLYlrFoFvtuFlLfmsePhfOZgtfThnh1umWxTIsxan1qkkYjvgXpzUMY2ifARjbxKhlicMQ58U5KWebSUkprXijmOXZ3cZ/LQw9a59+DqjWdOzZMm7dSUpFnMN0O5F5L5y4CoZ5yOgskFEEeiYS2rkadX3RXocP8f3QKD1Q1BPGIa+TqYUYYvasgZRaosqUAxkDKzCAEigFit1xL6njL4+Hl2LFfs/3UFhmWQ1IbWPJJbPPPELMHnKHcE8FJt8xYkvb4yeJyi4FE0uqb0bpQl/MQFKCo2iXGAH7JleOGoyqNXBfE0sH3GyX8Z3ZXiLIrhRTZqsLz6AAV++6jdsMnmoO0Fa+PsLX/PfUNBlrTY67MVVbujprqCS4LMWBPI9WZWvozujpwKncsiYAY6wZMk4s13jYGLOvuwuwvifW8pX+JK20Sts4eHwIl9qCmCqESNn1bAH2ir5MvmhlgrLViM1Q4kJh8T1v5mT/vgZ2bNW0x/cfQhUY/ig6F2BEMVXrCGANeJfEeNNevy9t1TrJ4Ncs3jpbYdZS7+pDb5Kmy/Tkcu3XbhYrcyYzyrZNsooHl0kY6x/SvzZUM58sMj8n4uQt4JApJ83f4Gn5x6AtNXZfH13rArhOfaBk7utPPF5KHEeuPeOQv7yHnbnpx6Fvx/grY8vZwo/+TFMT7/JTzjYNk2QesZthVeFsOu/7a3ej887H/FIzp5FRRN0="
    }
  }
}
