---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-app-secret
  namespace: apps
spec:
  encryptedData:
    api-key: AgAaz8EBiA9l1d/CMAuaSgsjlw56X+qiJWl2TLpGvVLxUeyWaO4VnrwNQ4yEXHiWMuXNjpz4bNv7HZQqQZcRzJsTF4OYAx0R2FJfp0KtkYZ4T5VFoi0AR77QzDZkMnMLEe6S9NWEEUPEtfTbyIT1sn8ALD9CKq796mPsPLoI6mDGY8J0LUHkGiMdyTSRjDmJyNUSJ2SCmJxARx9ZdvpZ+MDl4cZ35fzTE54pcZsUq9pY/n3IPQ6lWtaKBrKmgHCnFAU2BsnFkXrNZRcbmcpc+g5ypw5awjd1R9HBW8Gbvk5SAAYqT1DT6Nc0GUQg7S9RzzX20YdID0SDV2PwSIkFdMx8JjiAi5o6FGwrtcIQMx6sU8Yi2Hjh4lYHZOceAycWeYM366v0mtSkW3qBjuW5QReKJm/Wo/RL2hJUU8MHiBEOvV80SGcSs0flJNPb+G2oNbuQnqwkDQWoSADOX10NpnGx+TuTdRFZpsjspSws2wn8l3Z9PTzAhZV/MfsPHSo0tuMuTYkhIpKqhHOpiSq+4Ya6T06BqPSWr76+78g8TbHh4vYBj3+TtBoc75ckWYgIBa+0PUqDzQwHxRHddYTb8qAhJGSYkoaxWyBwUn/hlI1PMEpNzcyqpduv2vTBhFU18Ytgu4KY1E/Y41ly4aidjdC9fKvtIVaB5fbLwUUWVEDz1xr5bCWWNJOw8OoTAtTVXrErwuRceKV3axBAEiIlgoffCPDZ
  template:
    metadata:
      creationTimestamp: null
      name: demo-app-secret
      namespace: apps
