apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec: 
      volumes:
        - name: tmp
          emptyDir: {}
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: demo-app
          image: "{{ .Values.image.repository}}:{{.Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12}}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL