apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }} # metadata: name: demo-app
  namespace: {{ .Release.Namespace }} # spec:.destination.namespace in helm
spec:
  ingressClassName: nginx
  rules:
    - host: 74.220.20.237.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}
